# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('vkid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('deactivated', models.BooleanField()),
                ('ctype', models.SmallIntegerField(choices=[(0, 'Public page'), (1, 'Open group'), (2, 'Closed group'), (3, 'Private group')], db_column='type')),
                ('verified', models.NullBooleanField()),
                ('age_limit', models.SmallIntegerField(choices=[(-1, 'Unknown'), (0, 'No'), (16, '16+'), (18, '18+')], default=-1)),
                ('name', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('followers', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.TextField(blank=True)),
                ('icon50url', models.TextField(blank=True)),
                ('icon100url', models.TextField(blank=True)),
                ('posts_per_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('views_per_post', models.FloatField(blank=True, null=True)),
                ('likes_per_view', models.FloatField(blank=True, null=True)),
                ('growth_per_day', models.IntegerField(blank=True, null=True)),
                ('growth_per_week', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('followers', models.PositiveIntegerField()),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.Community')),
            ],
        ),
    ]
