# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_created_community_and_communityhistory_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='age_limit',
            field=models.SmallIntegerField(choices=[(-1, 'Unknown'), (0, 'None'), (16, '16+'), (18, '18+')], default=-1),
        ),
    ]
