# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-17 12:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_wallcheckinglog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('vkid', models.PositiveIntegerField()),
                ('published_at', models.DateTimeField()),
                ('content', django.contrib.postgres.fields.jsonb.JSONField()),
                ('views', models.PositiveIntegerField(blank=True, null=True)),
                ('likes', models.PositiveIntegerField()),
                ('shares', models.PositiveIntegerField()),
                ('comments', models.PositiveIntegerField()),
                ('marked_as_ads', models.BooleanField()),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.Community')),
            ],
        ),
    ]
