# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-19 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
