# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-19 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_filling_post_checked_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallcheckinglog',
            name='community',
        ),
        migrations.AddField(
            model_name='community',
            name='wall_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='WallCheckingLog',
        ),
    ]
