# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-26 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0008_delete_wallcheckinglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='links',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
