# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-28 09:35
from __future__ import unicode_literals

from django.db import migrations, models


def fill_links(apps, schema_editor):
    batch_size = 1000
    Post = apps.get_model('communities', 'Post')
    while True:
        post_ids = Post.objects.filter(links__isnull=True).values_list('id', flat=True)[:batch_size]
        if not post_ids:
            break
        Post.objects.filter(id__in=post_ids).update(links=0)


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('communities', '0009_post_links'),
    ]

    operations = [
        migrations.RunPython(fill_links, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='post',
            name='links',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
