# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-11 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0010_filling_post_links'),
        ('communities', '0004_change_fields_in_communityhistory'),
    ]

    operations = [
    ]
