# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-23 10:18
from __future__ import unicode_literals

from django.db import migrations

from communities.models import PostManager


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('communities', '0012_post_published_at_index'),
    ]

    operations = [
        migrations.RunSQL(
            'CREATE INDEX CONCURRENTLY "communities_post_likes_per_view_index" ON "communities_post" (({0}));'.format(
                PostManager.POST_LIKES_PER_VIEW_EXPRESSION
            ),
            'DROP INDEX "communities_post_likes_per_view_index";'
        )
    ]
