# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-24 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('communities', '0013_post_likes_per_view_index'),
    ]

    operations = [
        migrations.RunSQL(
            'CREATE INDEX CONCURRENTLY "communities_post_views_index" ON "communities_post" ("views");',
            'DROP INDEX "communities_post_views_index";'
        )
    ]
