# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-26 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('communities', '0014_post_views_index'),
    ]

    operations = [
        migrations.RunSQL(
            '''CREATE INDEX CONCURRENTLY "communities_post_content_fts_index" ON "communities_post" ''' +
            '''USING GIN((COALESCE(to_tsvector('russian', "content"), ''::tsvector)));''',
            'DROP INDEX "communities_post_content_fts_index";'
        )
    ]
