# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-23 10:48
from __future__ import unicode_literals

from django.db import migrations, transaction, connection
from django.db.models.expressions import RawSQL
from django.utils import timezone


def convert_post_content_to_new_format(apps, schema_editor):
    batch_size = 5000
    updates_per_vacuum = 500000
    Post = apps.get_model('communities', 'Post')
    now = timezone.now()
    updated_post_pub_time_min = now
    updated = 0
    updated_after_vacuum = 0
    while True:
        posts = Post.objects.annotate(
            has_old_format=RawSQL("""jsonb_array_length("content") > 0 and not ("content"->0 ? 'text')""", ())
        ).filter(
            checked_at__lt=now,
            published_at__lte=updated_post_pub_time_min,
            has_old_format=True
        ).order_by(
            '-published_at'
        ).only(
            'published_at', 'content'
        )[:batch_size]
        posts = list(posts)

        with transaction.atomic():
            for p in posts:
                p.content = [{'text': text} for text in p.content]
                p.save(update_fields=['content'])

        updated += len(posts)

        if len(posts) < batch_size:
            print('{} rows updated'.format(updated))
            vacuum()
            break

        updated_after_vacuum += len(posts)
        if updated_after_vacuum >= updates_per_vacuum:
            print('{} rows updated'.format(updated))
            vacuum()
            updated_after_vacuum = 0

        updated_post_pub_time_min = posts[-1].published_at


def vacuum():
    with connection.cursor() as c:
        c.execute('VACUUM communities_post;')


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('communities', '0015_post_content_fts_index'),
    ]

    operations = [
        migrations.RunPython(convert_post_content_to_new_format, migrations.RunPython.noop)
    ]
