# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-24 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0016_convert_post_content_to_new_format'),
    ]

    operations = [
        migrations.RunSQL(
            '''
            CREATE FUNCTION "post_content_to_tsvector" (config regconfig, content jsonb) RETURNS tsvector AS
            $$
            DECLARE
                res tsvector = to_tsvector(config, '');
                len int = jsonb_array_length(content);
                tmp text;
            BEGIN
                FOR i IN 0..(len-1) LOOP
                    tmp = content->i->>'text';
                    IF tmp IS NOT NULL THEN
                        res = res || to_tsvector(config, tmp);
                    END IF;
                END LOOP;
                RETURN res;
            END
            $$
            LANGUAGE plpgsql IMMUTABLE;''',

            '''DROP FUNCTION "post_content_to_tsvector";'''
        )
    ]
