# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-24 06:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('communities', '0017_post_content_to_tsvector_func'),
    ]

    operations = [
        migrations.RunSQL(
            '''CREATE INDEX CONCURRENTLY "communities_post_content_fts_index_v2" ON "communities_post" ''' +
            '''USING GIN(("post_content_to_tsvector"('russian', "content")));''',

            '''DROP INDEX "communities_post_content_fts_index_v2";'''
        )
    ]
